//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserTable
    {
        
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter required field")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Please enter required field")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter required field")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Please enter required field")]
        public string Roletype { get; set; }
        public Nullable<int> Dept_id { get; set; }
        public Nullable<int> RoleTypeID { get; set; }
    }
}
